@startuml
class Benutzer
class Eventeinreichung
class Eventreihe
class Event {
Basispreis
}
class PretixEvent
class PretixSubevent
class Poster
class Flyer
class Rundmail
class Standort
class EventSyncItem{
Letzter Export
Sync Foreign Key
---
CheckStatus()
}
class Publikationsdokument{
---
EntwurfErstellen()
}
class Publikation {
Datum
Inhalt
Entwurfsstatus
---
Publizieren()
}
Eventeinreichung -- Benutzer : Eigentümer >
Eventeinreichung --{ Benutzer : Miteinreicher >
Eventeinreichung --{ Event : Instanzen >
Event }-- Eventreihe : Teil von >
Event --{ EventSyncItem : Synchronisiert mit >
EventSyncItem <|-- PretixSubevent
EventSyncItem <|-- ErlangenKalenderEvent
EventSyncItem <|-- WordpressEvent
EventSyncItem <|-- NextcloudEvent
WordpressEvent }--- Standort : Veranstaltungsort >
NextcloudEvent }--- Standort : Veranstaltungsort >
PretixEvent ---{ Standort : Zuordnung >
PretixSubevent }--- Standort : Veranstaltungsort >
PretixEvent --{ PretixSubevent : Unterveranstaltungen >
Event }--{ Publikationsdokument : Enthaltene Veranstaltungen <
Publikationsdokument <|-- Poster
Publikationsdokument <|-- Flyer
Publikationsdokument <|-- Rundmail
Publikationsdokument --{ Publikation
@enduml