services:
  pretix:
    image: docker.io/pretix/standalone:2026.2.0
    ports:
      - "127.0.0.1:8282:80"
    volumes:
      - pretix_data:/data
    environment:
      PRETIX_ADMIN_EMAIL: ${PRETIX_ADMIN_EMAIL:-admin@localhost}
      PRETIX_ADMIN_PASSWORD: ${PRETIX_ADMIN_PASSWORD:-changeme}
      PRETIX_INSTANCE_NAME: ${PRETIX_INSTANCE_NAME:-ZAM Pretix (Debug)}
      PRETIX_URL: ${PRETIX_URL:-http://127.0.0.1:8282}
    restart: no

  grafana:
    image: grafana/grafana:latest
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    environment:
      GF_SERVER_ROOT_URL: "http://127.0.0.1:3000"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
    restart: no

  loki:
    image: grafana/loki:latest
    # This loki has no authentication.
    # NEVER EXPOSE ITS PORTS
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      # - loki_data:/data/loki/
    command: -config.file=/etc/loki/local-config.yaml
    restart: no

  alloy:
    image: grafana/alloy:latest
    # This alloy has no authentication.
    # NEVER EXPOSE ITS PORTS
    # ports:
    #   - 127.0.0.1:12345:12345
    #   - 127.0.0.1:4317:4317
    #   - 127.0.0.1:4318:4318
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./confs
        target: /etc/alloy/confs
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /var/log
        target: /var/log
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker/
        read_only: true
      - type: bind
        source: /run/udev/data
        target: /run/udev/data
        read_only: true
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
      - prometheus
    restart: no

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
    # This prometheus has no authentication.
    # NEVER EXPOSE ITS PORTS
    ports: # []
      - 127.0.0.1:9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: no

volumes:
  pretix_data:
  prometheus_data:
  grafana_data:
  loki_data:

