# Generated by Django 6.0.4 on 2026-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefaultvalue',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
