# Generated by Django 6.0.4 on 2026-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0002_fix_value_bool_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefaultvalue',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
