# Generated by Django 6.0.4 on 2026-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0003_fix_language_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
