# Generated by Django 6.0.4 on 2026-05-31 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0004_add_is_preview_to_field_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='data_type',
            field=models.CharField(choices=[('text_short', 'Text Short'), ('text_long', 'Text Long'), ('text_markdown', 'Text Markdown'), ('text_richtext', 'Text Richtext'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('select_single', 'Select Single'), ('select_multi', 'Select Multi'), ('image', 'Image'), ('file', 'File'), ('user_select', 'User Select'), ('user_select_multi', 'User Select Multi'), ('group_select', 'Group Select'), ('group_select_multi', 'Group Select Multi'), ('submodel_select', 'Submodel Select'), ('submodel_list', 'Submodel List'), ('entity_select', 'Entity Select'), ('entity_select_multi', 'Entity Select Multi'), ('slug_id', 'Slug Id')], max_length=30),
        ),
        migrations.CreateModel(
            name='SlugIdSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=200, unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('owner_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slug_sequences', to='userdefinedmodel.fieldconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
