# Generated by Django 6.0.4 on 2026-05-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0008_workflow_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstate',
            name='allows_edit',
        ),
    ]
