# Generated by Django 6.0.4 on 2026-05-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0011_remove_owner_editors'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtransition',
            name='unique_transition_name_per_workflow',
        ),
    ]
