# Generated by Django 6.0.4 on 2026-06-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0014_bulk_migration_submodel_and_workflow_state_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowdefinition',
            name='virtual_node_positions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
