# Generated by Django 6.0.4 on 2026-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdefinedmodel', '0015_workflow_virtual_node_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstate',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
    ]
