# Generated by Django 6.0.3 on 2026-03-15 10:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIDUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, default=uuid.uuid4, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('picture', models.URLField(blank=True, help_text='Profile picture URL')),
                ('locale', models.CharField(blank=True, help_text="User's locale (e.g., 'en-US')", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='User account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='User can access admin site')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('openid_subject', models.CharField(blank=True, db_index=True, help_text='OpenID Connect Subject (sub) claim from identity provider', max_length=255, null=True, unique=True)),
                ('openid_provider', models.CharField(blank=True, help_text="Name of the OpenID Connect identity provider (e.g., 'google', 'keycloak')", max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'OpenID User',
                'verbose_name_plural': 'OpenID Users',
                'db_table': 'openid_user_management_openid_user',
                'indexes': [models.Index(fields=['username'], name='openid_user_usernam_b524fd_idx'), models.Index(fields=['email'], name='openid_user_email_8b0fa1_idx'), models.Index(fields=['openid_subject'], name='openid_user_openid__ca531b_idx'), models.Index(fields=['openid_provider'], name='openid_user_openid__cfdd04_idx'), models.Index(fields=['is_active'], name='openid_user_is_acti_7995e6_idx'), models.Index(fields=['date_joined'], name='openid_user_date_jo_40c8e4_idx')],
            },
        ),
    ]
