# Generated by Django 6.0.3 on 2026-03-07 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('openid_user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openiduser',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='openiduser',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='openiduser',
            name='given_name',
        ),
        migrations.AddField(
            model_name='openiduser',
            name='username',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='openiduser',
            index=models.Index(fields=['username'], name='openid_user_usernam_b524fd_idx'),
        ),
    ]
