# Generated by Django 6.0.3 on 2026-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailqueueentry',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailqueueentry',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
