# Generated by Django 6.0.3 on 2026-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0002_alter_mailqueueentry_body_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailqueueentry',
            name='sender',
            field=models.EmailField(default='webmaster@localhost', max_length=254),
        ),
    ]
