# Generated by Django 6.0.3 on 2026-03-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0003_mailqueueentry_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailqueueentry',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='mailqueueentry',
            name='sent_at',
        ),
    ]
