# Generated by Django 6.0.3 on 2026-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0004_remove_mailqueueentry_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailqueueentry',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
