# Generated by Django 6.0.3 on 2026-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0005_alter_mailqueueentry_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailqueueentry',
            options={'ordering': ('created_at', 'recipient')},
        ),
        migrations.AlterField(
            model_name='mailqueueentry',
            name='sender',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
