# Generated by Django 6.0.3 on 2026-03-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0006_alter_mailqueueentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailqueueentry',
            options={'ordering': ('-created_at', 'recipient')},
        ),
    ]
