# Generated by Django 6.0.3 on 2026-03-09 13:59

import django.core.validators
import django.db.models.deletion
import pricing.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prep_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard-Vorbereitungszeit in Stunden', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vorbereitungszeit (Stunden)')),
                ('lecturer_rate', models.DecimalField(decimal_places=2, default=40.0, help_text='Honorar für Dozent:innen pro Stunde', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dozent:in Honorar pro Stunde (€)')),
                ('workshop_rate_basis', models.DecimalField(decimal_places=2, default=10.0, help_text='Stundensatz für Werkstatt & ZAM bei Grundkursen', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Werkstatt & ZAM Satz Grundkurs (€/h)')),
                ('workshop_rate_regular', models.DecimalField(decimal_places=2, default=20.0, help_text='Stundensatz für Werkstatt & ZAM bei regulären Kursen', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Werkstatt & ZAM Satz Regelfall (€/h)')),
                ('guest_surcharge', models.DecimalField(decimal_places=2, default=10.0, help_text='Aufschlag für Gäste pro Stunde', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gäst:in-Aufschlag (€/h)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Ermäßigungssatz als Dezimalzahl (z.B. 0.50 für 50%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ermäßigungssatz')),
                ('business_surcharge', models.DecimalField(decimal_places=2, default=0.75, help_text='Aufschlag für gewerbliche Teilnehmer als Dezimalzahl (z.B. 0.75 für 75%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewerbe-Aufschlag')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.07, help_text='Umsatzsteuersatz als Dezimalzahl (z.B. 0.07 für 7%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Umsatzsteuersatz')),
                ('min_participants_params', models.JSONField(default=pricing.models.default_min_participants_params, help_text='Parameter für Berechnung der Mindestteilnehmerzahl im Format {threshold: deduction}. Beispiel: {0: 1, 7: 2} bedeutet: Abzug von 1 für 1-6 Teilnehmer, Abzug von 2 für 7+ Teilnehmer. Formel: max_participants - deduction (wobei threshold <= max_participants)', verbose_name='Min. Teilnehmerzahl Parameter')),
            ],
            options={
                'verbose_name': 'Preiskonfiguration',
                'verbose_name_plural': 'Preiskonfiguration',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPricingConfiguration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('prep_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard-Vorbereitungszeit in Stunden', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vorbereitungszeit (Stunden)')),
                ('lecturer_rate', models.DecimalField(decimal_places=2, default=40.0, help_text='Honorar für Dozent:innen pro Stunde', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dozent:in Honorar pro Stunde (€)')),
                ('workshop_rate_basis', models.DecimalField(decimal_places=2, default=10.0, help_text='Stundensatz für Werkstatt & ZAM bei Grundkursen', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Werkstatt & ZAM Satz Grundkurs (€/h)')),
                ('workshop_rate_regular', models.DecimalField(decimal_places=2, default=20.0, help_text='Stundensatz für Werkstatt & ZAM bei regulären Kursen', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Werkstatt & ZAM Satz Regelfall (€/h)')),
                ('guest_surcharge', models.DecimalField(decimal_places=2, default=10.0, help_text='Aufschlag für Gäste pro Stunde', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gäst:in-Aufschlag (€/h)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Ermäßigungssatz als Dezimalzahl (z.B. 0.50 für 50%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ermäßigungssatz')),
                ('business_surcharge', models.DecimalField(decimal_places=2, default=0.75, help_text='Aufschlag für gewerbliche Teilnehmer als Dezimalzahl (z.B. 0.75 für 75%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gewerbe-Aufschlag')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.07, help_text='Umsatzsteuersatz als Dezimalzahl (z.B. 0.07 für 7%)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Umsatzsteuersatz')),
                ('min_participants_params', models.JSONField(default=pricing.models.default_min_participants_params, help_text='Parameter für Berechnung der Mindestteilnehmerzahl im Format {threshold: deduction}. Beispiel: {0: 1, 7: 2} bedeutet: Abzug von 1 für 1-6 Teilnehmer, Abzug von 2 für 7+ Teilnehmer. Formel: max_participants - deduction (wobei threshold <= max_participants)', verbose_name='Min. Teilnehmerzahl Parameter')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Preiskonfiguration',
                'verbose_name_plural': 'historical Preiskonfiguration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
