# Generated by Django 6.0.3 on 2026-03-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_alter_syncbasetarget_options_and_more'),
        ('sync_ical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalicalcalendersyncitem',
            name='sync_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.syncbasetarget'),
        ),
    ]
