# Generated by Django 6.0.3 on 2026-03-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_ical', '0002_historicalicalcalendersyncitem_sync_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icalcalendersyncitem',
            old_name='calendar',
            new_name='sync_target',
        ),
        migrations.RemoveField(
            model_name='historicalicalcalendersyncitem',
            name='calendar',
        ),
        migrations.AlterField(
            model_name='historicalicalcalendersyncitem',
            name='sync_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync_ical.icalcalendarsynctarget'),
        ),
    ]
