# Generated by Django 6.0.3 on 2026-03-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedprices',
            name='pricing_configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_prices', to='sync_pretix.pretixpricingconfiguration'),
        ),
        migrations.AddField(
            model_name='historicalcalculatedprices',
            name='pricing_configuration',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync_pretix.pretixpricingconfiguration'),
        ),
    ]
