# Generated by Django 6.0.3 on 2026-03-15 11:47

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_remove_historicalsyncbaseitem_sync_target_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sync_pretix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPretixSyncItem',
            fields=[
                ('syncbaseitem_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apiv1.syncbaseitem')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('flag_push', models.BooleanField(default=False)),
                ('event_slug', models.CharField(help_text='Slug of the Pretix event (has_subevents) that hosts the subevent.', max_length=255, verbose_name='Pretix Event Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('related_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.event')),
                ('sync_target', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync_pretix.pretixsynctarget')),
            ],
            options={
                'verbose_name': 'historical pretix sync item',
                'verbose_name_plural': 'historical pretix sync items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PretixSyncItem',
            fields=[
                ('syncbaseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiv1.syncbaseitem')),
                ('event_slug', models.CharField(help_text='Slug of the Pretix event (has_subevents) that hosts the subevent.', max_length=255, verbose_name='Pretix Event Slug')),
                ('sync_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_pretix.pretixsynctarget')),
            ],
            options={
                'abstract': False,
            },
            bases=('apiv1.syncbaseitem',),
        ),
    ]
