# Generated by Django 6.0.3 on 2026-03-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0003_pretixsyncitem_replace_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpretixsyncitem',
            name='area_association',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The area-to-event-slug mapping used when pushing to Pretix.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync_pretix.pretixsynctargetareaassociation', verbose_name='Area Association'),
        ),
    ]
