# Generated by Django 6.0.3 on 2026-03-14 21:08

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0015_syncbasetarget_historicalsyncbasetarget'),
        ('sync_pretix', '0003_convert_calculated_prices_money_fields_to_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PretixSyncTarget',
            fields=[
                ('syncbasetarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiv1.syncbasetarget')),
                ('api_token', models.CharField(help_text='API Token for authenticating with the Pretix API', max_length=255, verbose_name='Pretix API Token')),
                ('api_url', models.CharField(help_text='Pretix API URL', max_length=255, verbose_name='Pretix API URL')),
                ('organizer_slug', models.CharField(help_text='Organizer Slug', max_length=255, verbose_name='Organizer Slug')),
            ],
            options={
                'abstract': False,
            },
            bases=('apiv1.syncbasetarget',),
        ),
        migrations.CreateModel(
            name='HistoricalPretixSyncTarget',
            fields=[
                ('syncbasetarget_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apiv1.syncbasetarget')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('api_token', models.CharField(help_text='API Token for authenticating with the Pretix API', max_length=255, verbose_name='Pretix API Token')),
                ('api_url', models.CharField(help_text='Pretix API URL', max_length=255, verbose_name='Pretix API URL')),
                ('organizer_slug', models.CharField(help_text='Organizer Slug', max_length=255, verbose_name='Organizer Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pretix sync target',
                'verbose_name_plural': 'historical pretix sync targets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPretixSyncTargetAreaAssociation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('event_slug', models.CharField(help_text='Event Slug', max_length=255, verbose_name='Event Slug')),
                ('ticket_product_member_regular_id', models.CharField(blank=True, default='Regular Member Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Members (regular)')),
                ('ticket_product_member_discounted_id', models.CharField(blank=True, default='Discounted Member Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Members (discounted)')),
                ('ticket_product_guest_regular_id', models.CharField(blank=True, default='Regular Guest Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Guests (regular)')),
                ('ticket_product_guest_discounted_id', models.CharField(blank=True, default='Discounted Guest Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Guests (discounted)')),
                ('ticket_product_business_id', models.CharField(blank=True, default='Business Ticket', max_length=255, null=True, verbose_name='ID of Ticket Product for Businesses')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.proposalarea')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pretix sync target area association',
                'verbose_name_plural': 'historical pretix sync target area associations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PretixSyncTargetAreaAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_slug', models.CharField(help_text='Event Slug', max_length=255, verbose_name='Event Slug')),
                ('ticket_product_member_regular_id', models.CharField(blank=True, default='Regular Member Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Members (regular)')),
                ('ticket_product_member_discounted_id', models.CharField(blank=True, default='Discounted Member Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Members (discounted)')),
                ('ticket_product_guest_regular_id', models.CharField(blank=True, default='Regular Guest Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Guests (regular)')),
                ('ticket_product_guest_discounted_id', models.CharField(blank=True, default='Discounted Guest Ticket', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Guests (discounted)')),
                ('ticket_product_business_id', models.CharField(blank=True, default='Business Ticket', max_length=255, null=True, verbose_name='ID of Ticket Product for Businesses')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretix_sync_associations', to='apiv1.proposalarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
