# Generated by Django 6.0.3 on 2026-03-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sync_pretix', '0004_pretixsynctarget_historicalpretixsynctarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpretixsynctarget',
            name='polymorphic_ctype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
