# Generated by Django 6.0.3 on 2026-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0004_alter_historicalpretixsyncitem_area_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpretixsyncitem',
            name='pretix_data',
            field=models.JSONField(blank=True, default=None, help_text='Latest subevent and quota data fetched from Pretix after the most recent push. Structure: {"subevent": {...}, "quotas": [...]}', null=True, verbose_name='Pretix Subevent Data'),
        ),
        migrations.AddField(
            model_name='pretixsyncitem',
            name='pretix_data',
            field=models.JSONField(blank=True, default=None, help_text='Latest subevent and quota data fetched from Pretix after the most recent push. Structure: {"subevent": {...}, "quotas": [...]}', null=True, verbose_name='Pretix Subevent Data'),
        ),
    ]
