# Generated by Django 6.0.4 on 2026-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0005_add_pretixsyncitem_pretix_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedprices',
            name='internal_training_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Interne Fortbildung (EUR)'),
        ),
        migrations.AddField(
            model_name='historicalcalculatedprices',
            name='internal_training_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Interne Fortbildung (EUR)'),
        ),
    ]
