# Generated by Django 6.0.3 on 2026-03-14 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync_pretix", "0005_historicalpretixsynctarget_polymorphic_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpretixsynctargetareaassociation",
            name="sync_target",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sync_pretix.pretixsynctarget",
            ),
        ),
        migrations.AddField(
            model_name="pretixsynctargetareaassociation",
            name="sync_target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_associations",
                to="sync_pretix.pretixsynctarget",
            ),
        ),
    ]

