# Generated by Django 6.0.4 on 2026-05-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_pretix', '0006_add_internal_training_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpretixsynctargetareaassociation',
            name='ticket_product_internal_training_id',
            field=models.CharField(blank=True, default='Interne Fortbildung', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Internal Training'),
        ),
        migrations.AddField(
            model_name='pretixsynctargetareaassociation',
            name='ticket_product_internal_training_id',
            field=models.CharField(blank=True, default='Interne Fortbildung', max_length=255, null=True, verbose_name='ID or Name of Ticket Product for Internal Training'),
        ),
    ]
