// Import all editor files — side effects register each editor with the global registry
import './TextShortEditor'
import './TextLongEditor'
import './TextMarkdownEditor'
import './TextRichtextEditor'
import './SlugIdEditor'
import './NumberEditor'
import './BooleanEditor'
import './DateTimeEditors'
import './SelectSingleEditor'
import './SelectMultiEditor'
import './UserSelectEditor'
import './GroupSelectEditor'
import './EntitySelectEditor'
import './FileEditor'
import './WorkflowCellEditor'
import './SubmodelEditor'

export { fieldEditorRegistry } from './registry'
export { FieldInput } from './FieldInput'
export type { FieldInputProps } from './types'
export { getLang } from './types'
export { PolicyMessageList } from './shared'
