# Generated by Django 6.0.4 on 2026-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_caldav', '0002_caldavsynctarget_caldav_uid_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcaldavsyncitem',
            name='caldav_uid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaldavsynctarget',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
