# Generated by Django 6.0.4 on 2026-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_caldav', '0003_alter_historicalcaldavsyncitem_caldav_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caldavsyncitem',
            name='remote_ical_definition',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcaldavsyncitem',
            name='remote_ical_definition',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
