# Generated by Django 6.0.4 on 2026-05-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_caldav', '0004_caldavsyncitem_remote_ical_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldavsyncitem',
            name='caldav_uid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcaldavsyncitem',
            name='caldav_uid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
