import json

from django.core.management.base import BaseCommand


APIS = {
    "apiv1": "apiv1.api.api",
    "udm": "userdefinedmodel.api.api",
}


class Command(BaseCommand):
    help = "Print the OpenAPI schema generated by a Ninja API"

    def add_arguments(self, parser):
        parser.add_argument(
            "--api",
            choices=APIS.keys(),
            default="apiv1",
            help="Which API to generate the schema for (default: apiv1)",
        )

    def handle(self, *args, **options):
        from django.utils.module_loading import import_string
        api = import_string(APIS[options["api"]])
        schema = api.get_openapi_schema()
        self.stdout.write(json.dumps(schema, indent=2, sort_keys=True))

