import json

from django.core.management.base import BaseCommand

from apiv1.api import api


class Command(BaseCommand):
    help = "Print the OpenAPI schema generated by the apiv1 Ninja API"

    def handle(self, *args, **options):
        schema = api.get_openapi_schema()
        self.stdout.write(json.dumps(schema, indent=2, sort_keys=True))

