# Generated by Django 6.0.3 on 2026-03-07 23:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Generated by Django 6.0.3 on 2026-03-06 19:02

from django.db import migrations


def populate_submission_types(apps, schema_editor):
    """Populate SubmissionType lookup table with defaults from SubmissionForm.md"""
    SubmissionType = apps.get_model('apiv1', 'SubmissionType')

    submission_types = [
        {
            'code': 'workshop',
            'label': 'Workshop',
            'description': 'Fixed booking, fee required, providers receive a remuneration',
            'is_active': True,
            'sort_order': 10,
        },
        {
            'code': 'open_activity',
            'label': 'Open activity',
            'description': 'No booking or fee required; takes place in the main building',
            'is_active': True,
            'sort_order': 20,
        },
    ]

    for data in submission_types:
        SubmissionType.objects.get_or_create(
            code=data['code'],
            defaults={
                'label': data['label'],
                'description': data['description'],
                'is_active': data['is_active'],
                'sort_order': data['sort_order'],
            }
        )


def populate_proposal_languages(apps, schema_editor):
    """Populate ProposalLanguage lookup table with defaults from SubmissionForm.md"""
    ProposalLanguage = apps.get_model('apiv1', 'ProposalLanguage')

    languages = [
        {
            'code': 'de',
            'label': 'Deutsch',
            'description': '',
            'is_active': True,
            'sort_order': 10,
        },
        {
            'code': 'en',
            'label': 'English',
            'description': '',
            'is_active': True,
            'sort_order': 20,
        },
    ]

    for data in languages:
        ProposalLanguage.objects.get_or_create(
            code=data['code'],
            defaults={
                'label': data['label'],
                'description': data['description'],
                'is_active': data['is_active'],
                'sort_order': data['sort_order'],
            }
        )


def reverse_func(apps, schema_editor):
    """Reverse migration - remove the populated data"""
    SubmissionType = apps.get_model('apiv1', 'SubmissionType')
    ProposalLanguage = apps.get_model('apiv1', 'ProposalLanguage')

    SubmissionType.objects.filter(code__in=['workshop', 'open_activity']).delete()
    ProposalLanguage.objects.filter(code__in=['de', 'en']).delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProposalArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'verbose_name': 'Proposal area',
                'verbose_name_plural': 'Proposal areas',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'verbose_name': 'Proposal language',
                'verbose_name_plural': 'Proposal languages',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('biography', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(50)])),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='speaker_profiles/')),
                ('use_gravatar', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
            options={
                'verbose_name': 'Submission type',
                'verbose_name_plural': 'Submission types',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(50)])),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50)])),
                ('internal_notes', models.TextField(blank=True, max_length=2000)),
                ('occurrence_count', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.FileField(upload_to='proposal_photos/')),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_basic_course', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=0)),
                ('material_cost_eur', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_dates', models.TextField(max_length=1000)),
                ('is_regular_member', models.BooleanField(default=False)),
                ('has_building_access', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('associated_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_proposals', to='apiv1.event')),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_proposals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_proposals', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='apiv1.proposalarea')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='apiv1.proposallanguage')),
                ('associated_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_proposals', to='apiv1.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apiv1.series'),
        ),
        migrations.CreateModel(
            name='ProposalSpeaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary speaker'), ('co_speaker', 'Co-speaker')], default='co_speaker', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_speakers', to='apiv1.proposal')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_proposals', to='apiv1.speaker')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='speakers',
            field=models.ManyToManyField(related_name='proposals', through='apiv1.ProposalSpeaker', to='apiv1.speaker'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='submission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='apiv1.submissiontype'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['series', 'start_time'], name='apiv1_event_series__e1cab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalspeaker',
            constraint=models.UniqueConstraint(fields=('proposal', 'speaker'), name='unique_proposal_speaker'),
        ),
        migrations.AddConstraint(
            model_name='proposalspeaker',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('proposal',), name='unique_primary_speaker_per_proposal'),
        ),
        migrations.RunPython(populate_submission_types, reverse_func),
        migrations.RunPython(populate_proposal_languages, reverse_func),
    ]
