# Generated by Django 6.0.3 on 2026-03-08 00:22

from django.db import migrations


def add_proposal_areas(apps, schema_editor):
    ProposalArea = apps.get_model('apiv1', 'ProposalArea')

    areas = [
        {'code': 'holzwerkstatt', 'label': 'Holzwerkstatt', 'sort_order': 1},
        {'code': 'printing', 'label': 'Printing Workshop', 'sort_order': 2},
        {'code': 'color', 'label': 'Color Workshop', 'sort_order': 3},
        {'code': 'groundfloor', 'label': 'Open Groundfloor (Main Building)', 'sort_order': 4},
        {'code': 'tinkering', 'label': 'Tinkering Workshop and Bio Lab', 'sort_order': 5},
        {'code': 'prototyping', 'label': 'Prototyping Workshop and Electronics', 'sort_order': 6},
        {'code': 'textil', 'label': 'Textil Workshop', 'sort_order': 7},
        {'code': 'metal', 'label': 'Metal Workshop', 'sort_order': 8},
        {'code': 'kitchen', 'label': 'Community Kitchen', 'sort_order': 9},
    ]

    for area_data in areas:
        ProposalArea.objects.get_or_create(
            code=area_data['code'],
            defaults={
                'label': area_data['label'],
                'sort_order': area_data['sort_order'],
                'is_active': True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_proposal_areas, migrations.RunPython.noop),
    ]


