# Generated by Django 6.0.3 on 2026-03-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_add_proposal_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': [('browse_proposal', 'Can browse proposal list')]},
        ),
    ]
