# Generated by Django 6.0.3 on 2026-03-08 11:34

from django.db import migrations


def add_authenticated_users_group(apps, schema_editor):
    """Create Authenticated Users group with basic permissions."""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('openid_user_management', 'OpenIDUser')

    # Create or get the Authenticated Users group
    group, created = Group.objects.get_or_create(name='Authenticated Users')

    # Get or create the apiv1 content types (these may not exist yet if
    # the post_migrate signal hasn't run)
    proposal_ct, _ = ContentType.objects.get_or_create(app_label='apiv1', model='proposal')
    submission_type_ct, _ = ContentType.objects.get_or_create(app_label='apiv1', model='submissiontype')
    proposal_language_ct, _ = ContentType.objects.get_or_create(app_label='apiv1', model='proposallanguage')
    proposal_area_ct, _ = ContentType.objects.get_or_create(app_label='apiv1', model='proposalarea')

    # Define the permissions to add, creating them if they don't exist yet
    permission_definitions = [
        ('add_proposal', 'Can add proposal', proposal_ct),
        ('browse_proposal', 'Can browse proposal list', proposal_ct),
        ('view_submissiontype', 'Can view submission type', submission_type_ct),
        ('view_proposallanguage', 'Can view proposal language', proposal_language_ct),
        ('view_proposalarea', 'Can view proposal area', proposal_area_ct),
    ]

    # Add permissions to the group
    for codename, name, content_type in permission_definitions:
        permission, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=content_type,
            defaults={'name': name},
        )
        group.permissions.add(permission)

    # Add all existing users to the group
    for user in User.objects.all():
        user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_initial'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
        ('openid_user_management', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_authenticated_users_group, migrations.RunPython.noop),
    ]
