# Generated by Django 6.0.3 on 2026-03-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_authenticated_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncbasetarget',
            options={'permissions': [('viewrestricted_syncbasetarget', 'Can view restricted sync target information')]},
        ),
        migrations.AddField(
            model_name='historicalsyncbaseitem',
            name='sync_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.syncbasetarget'),
        ),
        migrations.AddField(
            model_name='syncbaseitem',
            name='sync_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='apiv1.syncbasetarget'),
        ),
    ]
