# Generated by Django 6.0.3 on 2026-03-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_alter_syncbasetarget_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsyncbaseitem',
            name='sync_target',
        ),
        migrations.RemoveField(
            model_name='syncbaseitem',
            name='sync_target',
        ),
    ]
