# Generated by Django 6.0.3 on 2026-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_syncbaseitem_historicalsyncbaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsyncbaseitem',
            name='flag_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsyncicalcalendar',
            name='flag_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsyncicalitem',
            name='flag_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncbaseitem',
            name='flag_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='proposal_photos/'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_profiles/'),
        ),
    ]
