# Generated by Django 6.0.3 on 2026-03-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_remove_historicalsyncbaseitem_sync_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncbaseitem',
            options={'permissions': [('push_syncbaseitem', 'Can push sync item to remote platform')]},
        ),
    ]
