# Generated by Django 6.0.3 on 2026-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_historicalevent_historicalproposal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': [('browse_proposal', 'Can browse proposal list'), ('accept_proposal', 'Can accept proposals (when the workflow allows it)'), ('reject_proposal', 'Can reject proposals (when the workflow allows it)'), ('submit_proposal', 'Can submit proposals (when the workflow allows it)'), ('revise_proposal', 'Can request for revision of proposals (when the workflow allows it)')]},
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revise', 'Revise'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revise', 'Revise'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
