# Generated by Django 6.0.4 on 2026-04-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_syncbaseitem_push_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspeaker',
            name='use_gravatar',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='use_gravatar',
        ),
    ]
