# Generated by Django 6.0.3 on 2026-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_alter_proposal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproposal',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='duration_time_per_day',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='proposal',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proposal',
            name='duration_time_per_day',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
