# Generated by Django 6.0.3 on 2026-03-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_historicalsyncbaseitem_flag_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='apiv1.proposal'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='proposal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.proposal'),
        ),
    ]
