# Generated by Django 6.0.4 on 2026-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_remove_historicalspeaker_use_gravatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='occurrence_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='occurrence_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
