# Generated by Django 6.0.3 on 2026-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_remove_historicalproposal_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='use_full_days',
            field=models.BooleanField(default=False, help_text='When checked, the event spans continuously over midnight. When unchecked, multi-day events are split into separate daily blocks using the start/end times of the first/last day.'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='use_full_days',
            field=models.BooleanField(default=False, help_text='When checked, the event spans continuously over midnight. When unchecked, multi-day events are split into separate daily blocks using the start/end times of the first/last day.'),
        ),
    ]
