# Generated by Django 6.0.3 on 2026-03-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_add_use_full_days_to_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproposal',
            name='associated_event',
        ),
        migrations.RemoveField(
            model_name='historicalproposal',
            name='associated_series',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='associated_event',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='associated_series',
        ),
    ]
