# Generated by Django 6.0.4 on 2026-05-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_alter_historicalproposal_occurrence_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproposal',
            name='is_regular_member',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='is_regular_member',
        ),
    ]
