# Generated by Django 6.0.3 on 2026-03-14 08:31

import apiv1.models.basedata
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_event_proposal_historicalevent_proposal'),
        ('apiv1', '0009_remove_historicalproposal_associated_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apiv1.models.basedata.UUIDFilenameUploadTo('proposal_photos')),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apiv1.models.basedata.UUIDFilenameUploadTo('speaker_profiles')),
        ),
    ]



