# Generated by Django 6.0.3 on 2026-03-14 08:41

import apiv1.models.basedata
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0010_alter_proposal_photo_alter_speaker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='historicalspeaker',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apiv1.models.basedata.UUIDFilenameUploadTo('proposal_photos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apiv1.models.basedata.UUIDFilenameUploadTo('speaker_profiles'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
