# Generated by Django 6.0.4 on 2026-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0011_call_proposal_call_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='submission_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='submission_deadline',
            field=models.DateField(),
        ),
    ]
