# Generated by Django 6.0.4 on 2026-05-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0012_call_submission_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apiv1.series'),
        ),
    ]
