# Generated by Django 6.0.3 on 2026-03-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0012_speaker_belongs_to_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalspeaker',
            name='proposal_id',
        ),
        migrations.AddField(
            model_name='historicalspeaker',
            name='proposal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apiv1.proposal'),
        ),
    ]
