# Generated by Django 6.0.4 on 2026-05-25 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0013_event_series_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('user', 'User review'), ('group', 'Group request')], max_length=10)),
                ('reviewer_is_system', models.BooleanField(default=False, help_text='True for the legacy moderation_comment migrated as a System review')),
                ('group_code', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revise', 'Revisions requested'), ('note', 'Informational note')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_directly', models.BooleanField(default=False)),
                ('requested_via_groups', models.JSONField(blank=True, default=list)),
                ('previous_status', models.CharField(blank=True, default='', max_length=10)),
                ('previous_comment', models.TextField(blank=True, default='')),
                ('migrated', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apiv1.proposal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
