# Generated by Django 6.0.3 on 2026-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0013_remove_historicalspeaker_proposal_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'permissions': [('submit_event', 'Can submit events (Draft → Proposed)'), ('approve_event', 'Can approve events (Proposed → Planned)'), ('reject_event', 'Can reject events (Proposed → Rejected)'), ('publish_event', 'Can publish events (Planned → Published)'), ('confirm_event', 'Can confirm events (Published → Confirmed)'), ('cancel_event', 'Can cancel events (Published → Canceled)'), ('complete_event', 'Can complete events (Confirmed → Completed)'), ('archive_event', 'Can archive events (Completed/Canceled/Rejected → Archived)')]},
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('planned', 'Planned'), ('published', 'Published'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('planned', 'Planned'), ('published', 'Published'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
