# Generated by Django 6.0.4 on 2026-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0014_proposalreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'permissions': [('browse_proposal', 'Can browse proposal list'), ('accept_proposal', 'Can accept proposals (when the workflow allows it)'), ('reject_proposal', 'Can reject proposals (when the workflow allows it)'), ('submit_proposal', 'Can submit proposals (when the workflow allows it)'), ('revise_proposal', 'Can request for revision of proposals (when the workflow allows it)'), ('moderate_proposal', 'Can write moderation comments on proposals'), ('create_review_proposal', 'Can create unsolicited reviews on any visible proposal')]},
        ),
    ]
