/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/udm/bulk-migrations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Bulk Migration */
        post: operations["userdefinedmodel_api_create_bulk_migration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Migration Preview */
        post: operations["userdefinedmodel_api_bulk_migration_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/{plan_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bulk Migration */
        get: operations["userdefinedmodel_api_get_bulk_migration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/bulk-migrations/{plan_id}/execute/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Bulk Migration Plan */
        post: operations["userdefinedmodel_api_execute_bulk_migration_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/config-versions/{version_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Version
         * @description Fetch a single config version by id (any status). Used to render an
         *     entity's form against its actual pinned version, even when archived.
         */
        get: operations["userdefinedmodel_api_get_config_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Configs */
        get: operations["userdefinedmodel_api_list_configs"];
        put?: never;
        /** Create Config */
        post: operations["userdefinedmodel_api_create_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["userdefinedmodel_api_get_config"];
        put?: never;
        post?: never;
        /** Delete Config */
        delete: operations["userdefinedmodel_api_delete_config"];
        options?: never;
        head?: never;
        /** Update Config */
        patch: operations["userdefinedmodel_api_update_config"];
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config Versions */
        get: operations["userdefinedmodel_api_list_config_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft Version */
        get: operations["userdefinedmodel_api_get_draft_version"];
        /** Replace Draft */
        put: operations["userdefinedmodel_api_replace_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/draft/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Draft */
        post: operations["userdefinedmodel_api_publish_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/configs/{config_id}/versions/published/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Published Version */
        get: operations["userdefinedmodel_api_get_published_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Entity */
        post: operations["userdefinedmodel_api_create_entity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["userdefinedmodel_api_get_entity"];
        put?: never;
        post?: never;
        /** Delete Entity */
        delete: operations["userdefinedmodel_api_delete_entity"];
        options?: never;
        head?: never;
        /** Patch Entity */
        patch: operations["userdefinedmodel_api_patch_entity"];
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity History */
        get: operations["userdefinedmodel_api_entity_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/migrate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Migration */
        post: operations["userdefinedmodel_api_execute_migration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/migration-preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Migration Preview */
        get: operations["userdefinedmodel_api_migration_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/policy-document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Policy Document */
        get: operations["userdefinedmodel_api_entity_policy_document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entities/{entity_id}/transition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Entity */
        post: operations["userdefinedmodel_api_transition_entity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/entity-search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Entities */
        get: operations["userdefinedmodel_api_search_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Groups */
        get: operations["userdefinedmodel_api_search_groups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/policies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["userdefinedmodel_api_list_policies"];
        put?: never;
        /** Create Policy */
        post: operations["userdefinedmodel_api_create_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/policies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["userdefinedmodel_api_get_policy"];
        /** Update Policy */
        put: operations["userdefinedmodel_api_update_policy"];
        post?: never;
        /** Delete Policy */
        delete: operations["userdefinedmodel_api_delete_policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/staging-files/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Staging File */
        post: operations["userdefinedmodel_api_upload_staging_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/staging-files/{staging_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Staging File */
        delete: operations["userdefinedmodel_api_delete_staging_file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Udm Types */
        get: operations["userdefinedmodel_api_list_udm_types"];
        put?: never;
        /** Create Udm Type */
        post: operations["userdefinedmodel_api_create_udm_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Udm Type */
        get: operations["userdefinedmodel_api_get_udm_type"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Udm Type */
        patch: operations["userdefinedmodel_api_update_udm_type"];
        trace?: never;
    };
    "/api/udm/types/{type_id}/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type Config */
        get: operations["userdefinedmodel_api_get_type_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/eval-policy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Policy For Type
         * @description Superuser-only: evaluate the Rego policy for a given entity + user and return the full
         *     input document, the raw policy sources, and the structured output.
         */
        get: operations["userdefinedmodel_api_eval_policy_for_type"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/policies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Policies */
        get: operations["userdefinedmodel_api_list_type_policies"];
        put?: never;
        /** Assign Policy */
        post: operations["userdefinedmodel_api_assign_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/types/{type_id}/policies/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Policy */
        delete: operations["userdefinedmodel_api_remove_policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/udm/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["userdefinedmodel_api_search_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllowedMimeTypesRuleIn */
        AllowedMimeTypesRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Mime Types */
            mime_types: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "allowed_mime_types";
        };
        /** BulkMigrationCreateIn */
        BulkMigrationCreateIn: {
            /** Field Mappings */
            field_mappings: components["schemas"]["MigrationFieldMappingIn"][];
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
            /** User Defined Model Type Filter Id */
            user_defined_model_type_filter_id?: string | null;
        };
        /** BulkMigrationOut */
        BulkMigrationOut: {
            /** Done Entities */
            done_entities: number;
            /** Executed At */
            executed_at: string | null;
            /** Failed Entities */
            failed_entities: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            status: components["schemas"]["BulkMigrationStatus"];
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
            /** Total Entities */
            total_entities: number;
            /** User Defined Model Type Filter Id */
            user_defined_model_type_filter_id: string | null;
        };
        /**
         * BulkMigrationStatus
         * @enum {string}
         */
        BulkMigrationStatus: "draft" | "running" | "done" | "partial";
        /** ConfigDraftIn */
        ConfigDraftIn: {
            /** Fields */
            fields: components["schemas"]["FieldDefinitionIn"][];
            /** Multi Field Rules */
            multi_field_rules?: components["schemas"]["MultiFieldRuleIn"][];
            /**
             * Notes
             * @default
             */
            notes: string;
            workflow?: components["schemas"]["WorkflowDefinitionIn"] | null;
        };
        /** ConfigLanguageIn */
        ConfigLanguageIn: {
            /** Code */
            code: string;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Label */
            label: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** ConfigLanguageOut */
        ConfigLanguageOut: {
            /** Code */
            code: string;
            /** Is Default */
            is_default: boolean;
            /** Label */
            label: string;
            /** Sort Order */
            sort_order: number;
        };
        /** ConfigVersionOut */
        ConfigVersionOut: {
            /** Fields */
            fields: components["schemas"]["FieldDefinitionOut"][];
            /** Languages */
            languages: components["schemas"]["ConfigLanguageOut"][];
            /** Notes */
            notes: string;
            /** Published At */
            published_at: string | null;
            /** Status */
            status: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            workflow?: components["schemas"]["WorkflowOut"] | null;
        };
        /**
         * DataType
         * @enum {string}
         */
        DataType: "text_short" | "text_long" | "text_markdown" | "text_richtext" | "integer" | "float" | "boolean" | "date" | "time" | "datetime" | "select_single" | "select_multi" | "image" | "file" | "user_select" | "user_select_multi" | "group_select" | "group_select_multi" | "submodel_select" | "submodel_list" | "entity_select" | "entity_select_multi";
        /** EditGroupOut */
        EditGroupOut: {
            /** Edits */
            edits: components["schemas"]["FieldEditOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Node Id
             * Format: uuid
             */
            node_id: string;
            /** Node Type */
            node_type: string;
            /** Saved At */
            saved_at: string;
            saved_by: components["schemas"]["UserRefOut"] | null;
        };
        /** EditHistoryOut */
        EditHistoryOut: {
            /** Count */
            count: number;
            /** Next */
            next: string | null;
            /** Results */
            results: components["schemas"]["EditGroupOut"][];
        };
        /** EntityAutocompleteItem */
        EntityAutocompleteItem: {
            /** Display */
            display: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type Id */
            type_id: string | null;
        };
        /** EntityCreateIn */
        EntityCreateIn: {
            /**
             * User Defined Model Type Id
             * Format: uuid
             */
            user_defined_model_type_id: string;
        };
        /** EntityOut */
        EntityOut: {
            /** Children */
            children: {
                [key: string]: unknown[];
            };
            /**
             * Config Version Id
             * Format: uuid
             */
            config_version_id: string;
            /** Created At */
            created_at: string;
            /** Current State */
            current_state: string | null;
            /** Editors */
            editors: components["schemas"]["UserRefOut"][];
            /** Field Values */
            field_values: components["schemas"]["FieldValueOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Overflow Data */
            overflow_data: {
                [key: string]: unknown;
            };
            owner: components["schemas"]["UserRefOut"] | null;
            /** Updated At */
            updated_at: string;
            /** User Defined Model Type Id */
            user_defined_model_type_id: string | null;
            /** Viewable Fields — null means no restriction (no policy) */
            viewable_fields: string[] | null;
            /** Editable Fields */
            editable_fields: string[];
        };
        /** EntityPatchIn */
        EntityPatchIn: {
            /** Changed Fields */
            changed_fields: {
                [key: string]: unknown;
            };
        };
        /** FieldConfigCreateIn */
        FieldConfigCreateIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Languages */
            languages: components["schemas"]["ConfigLanguageIn"][];
            /** Name */
            name: string;
        };
        /** FieldConfigOut */
        FieldConfigOut: {
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Languages */
            languages: components["schemas"]["ConfigLanguageOut"][];
            /** Name */
            name: string;
            /** Stale Entity Count */
            stale_entity_count: number;
            /** Type Ids */
            type_ids: string[];
        };
        /** FieldConfigUpdateIn */
        FieldConfigUpdateIn: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** FieldDefinitionIn */
        FieldDefinitionIn: {
            data_type: components["schemas"]["DataType"];
            /** Help Texts */
            help_texts?: {
                [key: string]: string;
            };
            /**
             * Is Localized
             * @default false
             */
            is_localized: boolean;
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Rules */
            rules?: (components["schemas"]["RequiredRuleIn"] | components["schemas"]["MinLengthRuleIn"] | components["schemas"]["MaxLengthRuleIn"] | components["schemas"]["RegexRuleIn"] | components["schemas"]["MinValueRuleIn"] | components["schemas"]["MaxValueRuleIn"] | components["schemas"]["MinItemsRuleIn"] | components["schemas"]["MaxItemsRuleIn"] | components["schemas"]["MaxFileSizeRuleIn"] | components["schemas"]["AllowedMimeTypesRuleIn"] | components["schemas"]["RequiredInLanguageRuleIn"])[];
            /** Slug */
            slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Submodel Config Version Id */
            submodel_config_version_id?: string | null;
            /** Type Config */
            type_config?: {
                [key: string]: unknown;
            };
        };
        /** FieldDefinitionOut */
        FieldDefinitionOut: {
            /** Data Type */
            data_type: string;
            /** Default */
            default?: unknown | null;
            /** Help Text */
            help_text: {
                [key: string]: string;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Localized */
            is_localized: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Save Rules */
            save_rules: {
                [key: string]: unknown;
            };
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            submodel_config?: components["schemas"]["ConfigVersionOut"] | null;
            /** Type Config */
            type_config: {
                [key: string]: unknown;
            };
        };
        /** FieldEditOut */
        FieldEditOut: {
            /** Affected Node Id */
            affected_node_id?: string | null;
            /** Change Kind */
            change_kind: string;
            /** Field Label */
            field_label?: string | null;
            /** Field Slug */
            field_slug?: string | null;
            /** New File Name */
            new_file_name?: string | null;
            /** New File Url */
            new_file_url?: string | null;
            /** New Value */
            new_value?: unknown | null;
            /** Old File Name */
            old_file_name?: string | null;
            /** Old File Url */
            old_file_url?: string | null;
            /** Old Value */
            old_value?: unknown | null;
        };
        /** FieldValueOut */
        FieldValueOut: {
            /** Data Type */
            data_type: string;
            /** Field Slug */
            field_slug: string;
            /**
             * Language
             * @default
             */
            language: string;
            /** Value */
            value: unknown;
        };
        /** GroupAutocompleteItem */
        GroupAutocompleteItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** MaxFileSizeRuleIn */
        MaxFileSizeRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Max Bytes */
            max_bytes: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "max_file_size";
        };
        /** MaxItemsRuleIn */
        MaxItemsRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Max Items */
            max_items: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "max_items";
        };
        /** MaxLengthRuleIn */
        MaxLengthRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Max Length */
            max_length: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "max_length";
        };
        /** MaxValueRuleIn */
        MaxValueRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Max Value */
            max_value: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "max_value";
        };
        /**
         * MigrationAction
         * @enum {string}
         */
        MigrationAction: "map" | "discard" | "overflow";
        /** MigrationExecuteIn */
        MigrationExecuteIn: {
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
            /** Field Mappings */
            field_mappings: components["schemas"]["MigrationFieldMappingIn"][];
            /**
             * Migration Id
             * Format: uuid
             */
            migration_id: string;
        };
        /** MigrationFieldMappingIn */
        MigrationFieldMappingIn: {
            action: components["schemas"]["MigrationAction"];
            /** Source Field Slug */
            source_field_slug: string;
            /** Target Field Slug */
            target_field_slug?: string | null;
        };
        /** MigrationPreviewFieldOut */
        MigrationPreviewFieldOut: {
            /** Conflict Reason */
            conflict_reason: string | null;
            /** Source Data Type */
            source_data_type: string;
            /** Source Slug */
            source_slug: string;
            suggested_action: components["schemas"]["MigrationAction"];
            /** Suggested Target Slug */
            suggested_target_slug: string | null;
        };
        /** MigrationPreviewOut */
        MigrationPreviewOut: {
            /** Field Previews */
            field_previews: components["schemas"]["MigrationPreviewFieldOut"][];
            /**
             * Migration Id
             * Format: uuid
             */
            migration_id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /**
             * Target Version Id
             * Format: uuid
             */
            target_version_id: string;
        };
        /** MinItemsRuleIn */
        MinItemsRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Min Items */
            min_items: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "min_items";
        };
        /** MinLengthRuleIn */
        MinLengthRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Min Length */
            min_length: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "min_length";
        };
        /** MinValueRuleIn */
        MinValueRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Min Value */
            min_value: number | string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "min_value";
        };
        /** MultiFieldRuleIn */
        MultiFieldRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Field Slugs */
            field_slugs: string[];
            kind: components["schemas"]["MultiFieldRuleKind"];
        };
        /**
         * MultiFieldRuleKind
         * @enum {string}
         */
        MultiFieldRuleKind: "at_least_one_required" | "exactly_one_required" | "mutual_exclusion";
        /** PolicyAssignIn */
        PolicyAssignIn: {
            /** Policy Slug */
            policy_slug: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** PolicyCreateIn */
        PolicyCreateIn: {
            /** Slug */
            slug: string;
            /** Source */
            source: string;
        };
        /** PolicyEvalOut */
        PolicyEvalOut: {
            /** Error */
            error?: string | null;
            /** Input Document */
            input_document: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            };
            /** Policies */
            policies: {
                [key: string]: string;
            }[];
        };
        /** PolicyOut */
        PolicyOut: {
            /** Slug */
            slug: string;
            /** Source */
            source: string;
        };
        /** PolicyUpdateIn */
        PolicyUpdateIn: {
            /** Source */
            source: string;
        };
        /** RegexRuleIn */
        RegexRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /**
             * Failure Message
             * @default
             */
            failure_message: string;
            /** Pattern */
            pattern: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "regex";
        };
        /** RequiredInLanguageRuleIn */
        RequiredInLanguageRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /** Language */
            language: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "required_in_language";
        };
        /** RequiredRuleIn */
        RequiredRuleIn: {
            /**
             * Admin Label
             * @default
             */
            admin_label: string;
            /**
             * Applies To Save
             * @default false
             */
            applies_to_save: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "required";
        };
        /** StagingFileOut */
        StagingFileOut: {
            /** Expires At */
            expires_at: string;
            /** Mime Type */
            mime_type: string;
            /** Original Name */
            original_name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Staging Id
             * Format: uuid
             */
            staging_id: string;
        };
        /** TransitionIn */
        TransitionIn: {
            /** Transition */
            transition: string;
        };
        /** UDMTypeCreateIn */
        UDMTypeCreateIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /** UDMTypeOut */
        UDMTypeOut: {
            /** Description */
            description: string;
            /** Field Config Id */
            field_config_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** UserAutocompleteItem */
        UserAutocompleteItem: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** UserRefOut */
        UserRefOut: {
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** WorkflowDefinitionIn */
        WorkflowDefinitionIn: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** States */
            states: components["schemas"]["WorkflowStateIn"][];
            /** Transitions */
            transitions?: components["schemas"]["WorkflowTransitionIn"][];
        };
        /** WorkflowOut */
        WorkflowOut: {
            /** Initial State */
            initial_state: string;
            /** States */
            states: components["schemas"]["WorkflowStateOut"][];
            /** Transitions */
            transitions: components["schemas"]["WorkflowTransitionOut"][];
        };
        /** WorkflowStateIn */
        WorkflowStateIn: {
            /**
             * Allows Edit
             * @default true
             */
            allows_edit: boolean;
            /**
             * Is Initial
             * @default false
             */
            is_initial: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
        };
        /** WorkflowStateOut */
        WorkflowStateOut: {
            /** Allows Edit */
            allows_edit: boolean;
            /** Is Initial */
            is_initial: boolean;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
        };
        /** WorkflowTransitionIn */
        WorkflowTransitionIn: {
            /** From State */
            from_state?: string | null;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /** To State */
            to_state: string;
        };
        /** WorkflowTransitionOut */
        WorkflowTransitionOut: {
            /** From State */
            from_state: string | null;
            /** Label */
            label: {
                [key: string]: string;
            };
            /** Name */
            name: string;
            /** To State */
            to_state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    userdefinedmodel_api_create_bulk_migration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkMigrationCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkMigrationOut"];
                };
            };
        };
    };
    userdefinedmodel_api_bulk_migration_preview: {
        parameters: {
            query: {
                source_version_id: string;
                target_version_id: string;
                type_filter_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_get_bulk_migration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkMigrationOut"];
                };
            };
        };
    };
    userdefinedmodel_api_execute_bulk_migration_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_get_config_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_list_configs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_create_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldConfigCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_delete_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_update_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldConfigUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConfigOut"];
                };
            };
        };
    };
    userdefinedmodel_api_list_config_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_get_draft_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_replace_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigDraftIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_publish_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_published_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_create_entity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_delete_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_patch_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityPatchIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entity_history: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditHistoryOut"];
                };
            };
        };
    };
    userdefinedmodel_api_execute_migration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrationExecuteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_migration_preview: {
        parameters: {
            query?: {
                target_user_defined_model_type?: string | null;
                target_version?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationPreviewOut"];
                };
            };
        };
    };
    userdefinedmodel_api_entity_policy_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_transition_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
        };
    };
    userdefinedmodel_api_search_entities: {
        parameters: {
            query?: {
                q?: string;
                type_ids?: string;
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAutocompleteItem"][];
                };
            };
        };
    };
    userdefinedmodel_api_search_groups: {
        parameters: {
            query?: {
                q?: string;
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAutocompleteItem"][];
                };
            };
        };
    };
    userdefinedmodel_api_list_policies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_create_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_update_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_delete_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_upload_staging_file: {
        parameters: {
            query?: {
                intended_field_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingFileOut"];
                };
            };
        };
    };
    userdefinedmodel_api_delete_staging_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staging_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_list_udm_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_create_udm_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UDMTypeCreateIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_udm_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_update_udm_type: {
        parameters: {
            query?: {
                field_config_id?: string | null;
            };
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UDMTypeOut"];
                };
            };
        };
    };
    userdefinedmodel_api_get_type_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigVersionOut"];
                };
            };
        };
    };
    userdefinedmodel_api_eval_policy_for_type: {
        parameters: {
            query: {
                entity_id: string;
                user_id: string;
                action?: string;
                transition?: string | null;
            };
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEvalOut"];
                };
            };
        };
    };
    userdefinedmodel_api_list_type_policies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
        };
    };
    userdefinedmodel_api_assign_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyAssignIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    userdefinedmodel_api_remove_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_id: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userdefinedmodel_api_search_users: {
        parameters: {
            query?: {
                q?: string;
                group_ids?: string;
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAutocompleteItem"][];
                };
            };
        };
    };
}
